name: "Plexamp"
version: "1.0.0"
slug: "plexamp"
description: "Plexamp headless player"
startup: application
boot: auto

arch:
  - aarch64
  - armv7
  - armhf

options:
  claim_token: ""
  player_name: "docker"

schema:
  claim_token: "str?"
  player_name: "str"

privileged:
  - SYS_ADMIN

devices:
  - /dev/snd:/dev/snd

ports:
  "32500/tcp": 32500
  "20000/tcp": 20000
  
image: ghcr.io/anatosun/plexamp
