name: Plexamp
slug: plexamp
version: "4.13.2"
description: Plexamp headless player

startup: application
boot: auto

arch:
  - aarch64

init: false
host_network: true

options:
  claim_token: ""
  player_name: "docker"

schema:
  claim_token: "str?"
  player_name: "str"

devices:
  - /dev/snd
  
webui: http://[HOST]:32500
#ports:
#  "32500/tcp": 32500
#  "20000/tcp": 20000

image: ghcr.io/anatosun/plexamp
